
spring.datasource.url=${DB_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Automatically creates/updates schema
spring.jpa.hibernate.ddl-auto=update

# Optional: show SQL logs
spring.jpa.show-sql=true

server.port=9090

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}
admin.email=${ADMIN_GMAIL}
admin.phone=${ADMIN_PHONE}



