package org.techm.capstone.restaurantManagementSystem.service;

import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.beans.factory.annotation.Autowired;
import org.techm.capstone.restaurantManagementSystem.model.*;
import org.techm.capstone.restaurantManagementSystem.repository.*;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
public class OrderStatusService {

    @Autowired
    private OrderStatusRepository orderStatusRepository;

    @Autowired
    private OrderHistoryRepository orderHistoryRepository;

    @Autowired
    private OrderRepository orderRepository;

    public void populateFromOrder(Order order) {
        if (order.getItems() == null) return;
        String username = order.getCustomer() != null ? order.getCustomer().getUsername() : "guest";
        for (OrderItem item : order.getItems()) {
            OrderStatus os = new OrderStatus(order.getId(), item.getDishName(), item.getQuantity(), order.getTableNumber(), username);
            orderStatusRepository.save(os);
        }
    }

    public List<OrderStatus> getAllFIFO() {
        // show all including IN_PROGRESS and READY_TO_SERVE but exclude COMPLETE
        return orderStatusRepository.findByStatusNotOrderByCreatedAtAsc(OrderStatus.Status.COMPLETE);
    }

    public List<OrderStatus> getNewFIFO() {
        return orderStatusRepository.findByStatusOrderByCreatedAtAsc(OrderStatus.Status.NEW);
    }

    public Optional<OrderStatus> getNextNew() {
        return orderStatusRepository.findFirstByStatusOrderByCreatedAtAsc(OrderStatus.Status.NEW);
    }

    public OrderStatus findById(Long id) {
        return orderStatusRepository.findById(id).orElseThrow();
    }

    @Transactional
    public void updateStatus(Long id, OrderStatus.Status newStatus) {
        OrderStatus os = orderStatusRepository.findById(id).orElseThrow();
        if (newStatus == OrderStatus.Status.COMPLETE) {
            OrderHistory history = new OrderHistory(
                    os.getOrderId(),
                    os.getDishName(),
                    os.getQuantity(),
                    os.getTableNumber(),
                    os.getUsername(),
                    OrderStatus.Status.COMPLETE,
                    LocalDateTime.now()
            );
            orderHistoryRepository.save(history);   // history.id will be generated by JPA
            orderStatusRepository.deleteById(id);   // remove active row
        } else {
            os.setStatus(newStatus);
            orderStatusRepository.save(os);
        }
    }


//    @Transactional
//    public Optional<OrderStatus> claimNextNewAndMarkInProgress() {
//        Optional<OrderStatus> next = orderStatusRepository.findFirstByStatusOrderByCreatedAtAsc(OrderStatus.Status.NEW);
//        if (next.isPresent()) {
//            OrderStatus os = next.get();
//            os.setStatus(OrderStatus.Status.IN_PROGRESS);
//            orderStatusRepository.save(os);
//            return Optional.of(os);
//        }
//        return Optional.empty();
//    }
//
//    @Transactional
//    public void migrateExistingOrders() {
//        List<Order> orders = orderRepository.findAll();
//        for (Order order : orders) {
//            String username = order.getCustomer() != null ? order.getCustomer().getUsername() : "guest";
//            for (OrderItem item : order.getItems()) {
//                OrderStatus os = new OrderStatus(order.getId(), item.getDishName(), item.getQuantity(), order.getTableNumber(), username);
//                orderStatusRepository.save(os);
//            }
//        }
//    }
    @Transactional
    public void updateWholeOrderStatus(Long orderId, OrderStatus.Status newStatus) {
        List<OrderStatus> items = orderStatusRepository.findAll()
                .stream()
                .filter(os -> Objects.equals(os.getOrderId(), orderId))
                .collect(Collectors.toList());

        if (newStatus == OrderStatus.Status.COMPLETE) {
            for (OrderStatus os : items) {
                OrderHistory history = new OrderHistory(
                        os.getOrderId(),
                        os.getDishName(),
                        os.getQuantity(),
                        os.getTableNumber(),
                        os.getUsername(),
                        OrderStatus.Status.COMPLETE,
                        LocalDateTime.now()
                );
                orderHistoryRepository.save(history);
                orderStatusRepository.deleteById(os.getId());
            }
        } else {
            for (OrderStatus os : items) {
                os.setStatus(newStatus);
            }
            orderStatusRepository.saveAll(items);
        }
    }
}
